# Site settings
title: Wee Blog
SEOTitle: Wee Blog
header-img: img/home-bg.jpg
email: lchang199x@gmail.com
description: "Weenote Developer Blog."
keyword: "Weenote, Cliu, Android, Developer, Blog, Homepage"
url: "http://lchang199x.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: https://github.com/lchang199x/lchang199x.github.io # you code repository
theme_repo: https://github.com/Huxpro/huxpro.github.io # the theme repository
download: /download/latest/weenote-1.0.0.apk

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Everything ends at some point!"
sidebar-avatar: /img/about.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     weenote
github_username:    lchang199x


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: lchang199x

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 259834b092f13ee03a19                            #生成的clientID
  clientSecret: b111b936f1d8682ea4d39c44df54894b246ed182    #生成的clientSecret
  repo: lchang199x.github.io    #仓库名称
  owner: lchang199x    #github用户名
  admin: lchang199x
  distractionFreeMode: false #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: weenote.cn               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Links
friends: [
    {
        title: "Android Developer",
        href: "https://developer.android.google.cn/"
    },{
        title: "Wikipedia",
        href: "https://en.wikipedia.org/"
    },{
        title: "Pexels",
        href: "https://www.pexels.com/"
    },{
        title: "Library Genesis",
        href: "http://gen.lib.rus.ec/"
    },{
        title: "Weenote",
        href: "https://github.com/lchang199x/lchang199x.github.io/releases/download/v1.0.0/weenote-1.0.0.apk"
    }
]
